package com.java.moudle.system.domain;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.DictUtil;
import com.java.until.dba.BaseDomain;

/**
 * 检查项目字典表(sys_exam_item)
 * 
 * @author tz
 * @version 1.0.0 2020-06-24
 */
@Entity
@Table(name = "sys_exam_item")
public class SysExamItem extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 289276889193021910L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @Id
    private String id;

    /** 项目代码 */
    private String itemCode;

    /** 标本类型 */
    private String sampleType;

    /** 项目组别 */
    private String itemGroup;

    /** 数据类型 */
    private String dataType;

    /** 单位 */
    private String unit;

    /** 参考值下限 */
    private String minValue;

    /** 参考值上限 */
    private String maxValue;

    /** 参考值打印 */
    private String printValue;

    /** 创建日期 */
    @JSONField(format = "yyyy-MM-dd")
    @Column(updatable = false)
    private Date createTime;

    /** 项目名称 */
    private String name;

    @Transient
    private String nameOrCode;
    @Transient
    private String itemGroupName;
    @Transient
    private String sampleTypeName;
    
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取项目代码
     * 
     * @return 项目代码
     */
    public String getItemCode() {
        return this.itemCode;
    }

    /**
     * 设置项目代码
     * 
     * @param itemCode
     *          项目代码
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * 获取标本类型
     * 
     * @return 标本类型
     */
    public String getSampleType() {
        return this.sampleType;
    }

    /**
     * 设置标本类型
     * 
     * @param sampleType
     *          标本类型
     */
    public void setSampleType(String sampleType) {
        this.sampleType = sampleType;
    }

    /**
     * 获取项目组别
     * 
     * @return 项目组别
     */
    public String getItemGroup() {
        return this.itemGroup;
    }

    /**
     * 设置项目组别
     * 
     * @param itemGroup
     *          项目组别
     */
    public void setItemGroup(String itemGroup) {
    	this.itemGroupName = DictUtil.getDictValue("itemGroupOpt", itemGroup);
        this.itemGroup = itemGroup;
    }

    /**
     * 获取数据类型
     * 
     * @return 数据类型
     */
    public String getDataType() {
        return this.dataType;
    }

    /**
     * 设置数据类型
     * 
     * @param dataType
     *          数据类型
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * 获取单位
     * 
     * @return 单位
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * 设置单位
     * 
     * @param unit
     *          单位
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * 获取参考值下限
     * 
     * @return 参考值下限
     */
    public String getMinValue() {
        return this.minValue;
    }

    /**
     * 设置参考值下限
     * 
     * @param minValue
     *          参考值下限
     */
    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }

    /**
     * 获取参考值上限
     * 
     * @return 参考值上限
     */
    public String getMaxValue() {
        return this.maxValue;
    }

    /**
     * 设置参考值上限
     * 
     * @param maxValue
     *          参考值上限
     */
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * 获取参考值打印
     * 
     * @return 参考值打印
     */
    public String getPrintValue() {
        return this.printValue;
    }

    /**
     * 设置参考值打印
     * 
     * @param printValue
     *          参考值打印
     */
    public void setPrintValue(String printValue) {
        this.printValue = printValue;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取项目名称
     * 
     * @return 项目名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置项目名称
     * 
     * @param name
     *          项目名称
     */
    public void setName(String name) {
        this.name = name;
    }

	public String getNameOrCode() {
		return nameOrCode;
	}

	public void setNameOrCode(String nameOrCode) {
		this.nameOrCode = nameOrCode;
	}

	public String getItemGroupName() {
		return itemGroupName;
	}

	public void setItemGroupName(String itemGroupName) {
		this.itemGroupName = itemGroupName;
	}

	public String getSampleTypeName() {
		return sampleTypeName;
	}

	public void setSampleTypeName(String sampleTypeName) {
		this.sampleTypeName = sampleTypeName;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}