package com.java.moudle.system.domain;


import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.java.until.DictUtil;
import com.java.until.dba.BaseDomain;

/**
 * 检查项目组合字典表(sys_exam_assoc)
 * 
 * @author tz
 * @version 1.0.0 2020-06-24
 */
@Entity
@Table(name = "sys_exam_assoc")
public class SysExamAssoc extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 1094195903624223764L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @Id
    private String id;

    /** 名称 */
    private String name;

    /** 组合代码 */
    private String assocCode;

    /** 标本类型 */
    private String sampleType;

    /** 项目组别 */
    private String itemGroup;
    
    @JSONField(format = "yyyy-MM-dd")
    @Column(updatable = false)
    private Date createTime;
    
    @Transient
    private String itemIdStr;
    @Transient
    private String itemNameStr;
    @Transient
    private String itemGroupName;
    @Transient
    private String sampleTypeName;
    @Transient
    private List<SysExamItem> examItemList;//项目组合关系集合

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    

    public String getAssocCode() {
		return assocCode;
	}

	public void setAssocCode(String assocCode) {
		this.assocCode = assocCode;
	}

	public String getItemGroup() {
		return itemGroup;
	}

	public void setItemGroup(String itemGroup) {
		this.itemGroupName = DictUtil.getDictValue("itemGroupOpt", itemGroup);
		this.itemGroup = itemGroup;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
     * 获取sampleType
     * 
     * @return sampleType
     */
    public String getSampleType() {
        return this.sampleType;
    }

    /**
     * 设置sampleType
     * 
     * @param sampleType
     */
    public void setSampleType(String sampleType) {
        this.sampleType = sampleType;
    }

	public String getItemIdStr() {
		return itemIdStr;
	}

	public void setItemIdStr(String itemIdStr) {
		this.itemIdStr = itemIdStr;
	}

	public String getItemNameStr() {
		return itemNameStr;
	}

	public void setItemNameStr(String itemNameStr) {
		this.itemNameStr = itemNameStr;
	}

	public List<SysExamItem> getExamItemList() {
		return examItemList;
	}

	public void setExamItemList(List<SysExamItem> examItemList) {
		this.examItemList = examItemList;
	}

	public String getItemGroupName() {
		return itemGroupName;
	}

	public void setItemGroupName(String itemGroupName) {
		this.itemGroupName = itemGroupName;
	}

	public String getSampleTypeName() {
		return sampleTypeName;
	}

	public void setSampleTypeName(String sampleTypeName) {
		this.sampleTypeName = sampleTypeName;
	}



    /* This code was generated by TableGo tools, mark 2 end. */
}