package com.java.moudle.system.domain;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.java.until.dba.BaseDomain;

/**
 * 检查项目组合关系表(sys_item_assoc)
 * 
 * @author tz
 * @version 1.0.0 2020-06-24
 */
@Entity
@Table(name = "sys_item_assoc")
public class SysItemAssoc extends BaseDomain {
    /** 版本号 */
    private static final long serialVersionUID = 76794771982269881L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @Id
    private String id;

    /** itemId */
    @Column(name="item_id")
    private String itemId;

    /** assocId */
    @Column(name="assoc_id")
    private String assocId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取itemId
     * 
     * @return itemId
     */
    public String getItemId() {
        return this.itemId;
    }

    /**
     * 设置itemId
     * 
     * @param itemId
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取assocId
     * 
     * @return assocId
     */
    public String getAssocId() {
        return this.assocId;
    }

    /**
     * 设置assocId
     * 
     * @param assocId
     */
    public void setAssocId(String assocId) {
        this.assocId = assocId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}